---
title: "Anthony Yoskovich"
output: 
  html_document: 
    theme: readable
    css: "style.css"
---

Analytics practitioner with experience solving problems using data and visualizing quantitative information.

 [`r ico("github", NULL)` github](https://github.com/ayoskovich), [`r ico("globe-americas")` personal site](https://anthonyyoskovich.com/), `r ico("envelope")` `r 'anthony.yoskovich@gmail.com'`

****

## `r ico("file-alt")` Experience

<!-- Hackin my way downtown... -->
<h4 class="work_title">Data Analyst <span class="work_company"> - National Heritage Academies</span></h4> <h4 class="work_dates">March 2021 - Present</h4>
<div style="clear: both"></div>
- Developed a risk-adjusted linear model in `Python` to classify more than 50,000 attendance rates.
  - Hosted the results on a company-wide instance of `Tableau Server`.
- Consulted with SMEs to leverage data to prioritize and inform classroom instruction.
  - Facilitated semi-weekly discussions of student academic trends and relationships.
- Automated the conversion of over 1,000 PDF files into a tabular format using the `Tesseract` OCR engine in `R`.
  - Saved more than 80 hours of manual work each year.
- Verified data integrity of more than 15 million records in the data warehouse using `Python`, `R`, and `SQL`.
- Regularly analyzed and visualized complex testing results of 4 subjects at more than 50 schools using `ggplot2`.

<h4 class="work_title">Optimization Consultant <span class="work_company"> - Betting Hero</span></h4> <h4 class="work_dates">May 2020 - March 2021</h4>
<div style="clear: both"></div>
- Built a live dashboard in Google Sheets to track mission critical KPIs across 24 events in 4 states.
- Automated a scheduling application using `Google Apps Script` to save 10 hrs of manual work per week.
- Used the `Google Sheets API` and `Python` to streamline recruitment efforts of over 400 employees.

<h4 class="work_title">Advanced Analytics Intern <span class="work_company"> - Steelcase</span></h4> <h4 class="work_dates">May 2019 - May 2020</h4>
<div style="clear: both"></div>
- Delivered data-driven hiring and relocation insights by modeling $60 million worth of incremental sales.
- Investigated and presented share of wallet variability using `R Shiny` to inform strategic sales tactics.
- Worked on a cross-functional team to deploy a floor space optimization tool and recommender system.
- Used `Python`, `R`, `Tableau`, and `SAS` to clean, merge, analyze, and summarize over 50 million rows of data.

****

## `r ico("flask")` Personal Projects
[`r ico("link")`](https://anthonyyoskovich.com/) Occasional blogging and tinkering around on my website built with `R Markdown` and hosted on `Netlify`.

[`r ico("link")`](https://amisaving.herokuapp.com/myapp) Developed and deployed an interactive cost saving dashboard using `Python`, `Heroku`, and `Bokeh`.

[`r ico("link")`](https://anthonyyoskovich.com/project/internet-traffic/) Created a `Python` script to log my internet speed and analyzed 800,000 data-points with `pandas` and `seaborn`.

[`r ico("link")`](https://www.youtube.com/watch?v=KQN2H1IuiuM&t=2s) Built a Raspberry Pi data logger with `Python` to archive the price of `Bitcoin` using the `Cryptowatch` API.

****

## `r ico("clipboard-list")` Technologies
- **`R`**, `R Markdown`, `tidyverse`, `janitor`, `leaflet`
- **`Python`**, `pandas`, `sklearn`, `seaborn`
- `Tableau`, `Tableau Server`
- `SQL`, `git`, `vim`, `cron`, `tmux`
- `Azure DevOps`, `Asana`, `GitHub`
- `Netlify`, `Heroku`, `shinyapps.io`

****

## `r ico("university")` Education
#### Grand Valley State University (April 2020)
- Bachelor of Science in Statistics & Economics (3.7 / 4.0)
- Minor in Mathematics
- Dean's List every semester

<br>

<sup>*</sup> This document was created entirely using `R Markdown` and the source code can be found on [`github`](https://github.com/ayoskovich/resume).